#!/usr/bin/env python3
"""Derive the Swarm counterpart from the root Compose source of truth.

Compatibility exceptions are intentionally narrow:
* Swarm uses legacy Compose v3.8 and an overlay network.
* Compose startup dependencies are removed; Swarm does not sequence readiness.
* restart becomes deploy.restart_policy, with one replica and stop-first updates.
* Local PostgreSQL, MinIO, and Search volumes require a labeled data node.
* Nginx's three repository file mounts become configs and a TLS key secret.
* Backup is opt-in through a separate Swarm overlay; Compose restore selections are excluded.
* Checked-in source selection defaults are inlined without interpolation; other
  required environment-file paths are relative to the generated stack.

Images, environment, commands, health checks, ports, and application volumes
otherwise remain identical. AI remains present; the Backup overlay requires a matching Swarm-capable image.
Test-only settings belong in the local test overlay, never in this counterpart.
This file never reads .env or resolves environment variables.
"""
from __future__ import annotations

import argparse
import copy
from pathlib import Path, PurePosixPath
import re
import sys

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'docker-compose.yml'
TARGET = Path(__file__).resolve().parent / 'docker-stack.yml'
BACKUP_SOURCE = ROOT / 'docker-compose.backup.yml'
BACKUP_TARGET = TARGET.with_name('docker-stack.backup.yml')
DATA_SERVICES = {'postgres', 'minio', 'appflowy_search'}
DATA_CONSTRAINT = 'node.labels.appflowy.data == true'
HEADER = (
    '# Generated by python3 docker-swarm/generate.py from ../docker-compose.yml.\n'
    '# Do not edit this file; update the root Compose source and regenerate.\n'
    '# Swarm startup sequencing and data-node labeling are documented in README.md.\n'
    '# Backup uses a separate overlay; Compose selections are excluded. See README.md#backup-and-restore.\n'
)


def supported_services(source: dict) -> dict:
    """Keep the reviewed Swarm service set; never turn profiles into enabled services."""
    services = {}
    for name, service in source['services'].items():
        if name == 'appflowy_backup' and service.get('profiles') == ['backup']:
            continue
        if 'profiles' in service or name == 'appflowy_backup':
            raise ValueError(f'{name}: profile/Backup deployment needs an explicit Swarm adapter.')
        services[name] = service
    return services


def rebase_path(value: str) -> str:
    """The generated artifact lives one directory below the Compose source."""
    if value.startswith('/'):
        return value
    if '$' in value:
        raise ValueError('Variable env_file paths require an explicit Swarm conversion.')
    return str(PurePosixPath('..') / value)


def source_defaults(name: str) -> dict:
    """Read the reviewed literal templates, never an operator environment or restore state."""
    path = ROOT / 'docker' / 'backup' / f'source-{name}.env'
    result = {}
    for line in path.read_text().splitlines():
        if not line or line.startswith('#'):
            continue
        match = re.fullmatch(r'([A-Z][A-Z0-9_]*)=(\$\{[A-Z][A-Z0-9_]*(?::-[^\'"}\n]*)?\})', line)
        if not match:
            raise ValueError(f'{path.relative_to(ROOT)} contains a non-template value; review Swarm conversion.')
        result[match[1]] = match[2]
    return result


def convert_environment(name: str, service: dict) -> None:
    """Preserve source values and environment precedence without loading local restore files."""
    files = service.pop('env_file', [])
    if isinstance(files, str):
        files = [files]
    defaults = {}
    required_files = []
    for entry in files:
        path = entry if isinstance(entry, str) else entry.get('path')
        if not isinstance(path, str):
            raise ValueError(f'{name}: env_file needs a path.')
        if entry == {'path': f'./backup-ops/runtime/selection-{name}.env',
                     'required': False, 'format': 'raw'}:
            # These are private Compose coordinator selections, not Swarm state.
            continue
        if path == f'./docker/backup/source-{name}.env':
            if not isinstance(entry, str) and entry != {'path': path}:
                raise ValueError(f'{name}: source environment-file semantics changed.')
            defaults.update(source_defaults(name))
            continue
        if not isinstance(entry, str):
            if entry.get('required', True) is not True or set(entry) - {'path', 'required'}:
                raise ValueError(f'{name}: optional/raw env_file needs an explicit Swarm conversion.')
        required_files.append(rebase_path(path))
    if required_files:
        if defaults:
            raise ValueError(f'{name}: mixed source defaults and extra env_files need a precedence review.')
        service['env_file'] = required_files
    if defaults:
        environment = service.get('environment', {})
        if isinstance(environment, list):
            explicit = {item.split('=', 1)[0] for item in environment}
            service['environment'] = [f'{key}={value}' for key, value in defaults.items()
                                      if key not in explicit] + environment
        else:
            service['environment'] = {**defaults, **environment}


def derive(source: dict) -> dict:
    stack = {'version': '3.8', **copy.deepcopy(source)}
    stack['services'] = copy.deepcopy(supported_services(source))
    for name, service in stack['services'].items():
        convert_environment(name, service)
        service.pop('depends_on', None)
        restart = service.pop('restart', 'no')
        conditions = {'no': 'none', 'on-failure': 'on-failure', 'always': 'any', 'unless-stopped': 'any'}
        if restart not in conditions:
            raise ValueError(f'Unsupported restart policy for {name}: {restart}; update the compatibility conversion explicitly.')
        if 'deploy' in service:
            raise ValueError(f'{name} now defines deploy in the source; review how it merges with Swarm defaults.')
        service['deploy'] = {
            # Swarm defaults to one replica. Older Docker CLIs incorrectly merge
            # an explicit 1 with a bootstrap override of 0, retaining the 1.
            'restart_policy': {'condition': conditions[restart]},
            'update_config': {'parallelism': 1, 'order': 'stop-first'},
        }
        if name in DATA_SERVICES:
            service['deploy']['placement'] = {'constraints': [DATA_CONSTRAINT]}

    nginx = stack['services']['nginx']
    expected_mounts = [
        './docker/nginx/nginx.conf:/etc/nginx/nginx.conf',
        './docker/nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt',
        './docker/nginx/ssl/private_key.key:/etc/nginx/ssl/private_key.key',
    ]
    if nginx.get('volumes') != expected_mounts:
        raise ValueError('Root Nginx mounts changed; update the explicit configs/secrets conversion before regenerating.')
    if 'configs' in source or 'secrets' in source or 'networks' in source:
        raise ValueError('Root networks/configs/secrets changed; review their Swarm conversion explicitly.')
    nginx.pop('volumes')
    nginx['configs'] = [
        {'source': 'nginx_config', 'target': '/etc/nginx/nginx.conf'},
        {'source': 'tls_certificate', 'target': '/etc/nginx/ssl/certificate.crt'},
    ]
    nginx['secrets'] = [
        {'source': 'tls_private_key', 'target': '/etc/nginx/ssl/private_key.key', 'mode': 0o400},
    ]
    stack['networks'] = {'default': {'driver': 'overlay'}}
    stack['configs'] = {
        'nginx_config': {'file': '../docker/nginx/nginx.conf'},
        'tls_certificate': {'file': '../docker/nginx/ssl/certificate.crt'},
    }
    stack['secrets'] = {'tls_private_key': {'file': '../docker/nginx/ssl/private_key.key'}}
    return stack


def environment_map(value: dict | list) -> dict:
    if isinstance(value, dict):
        return value
    return dict(item.split('=', 1) for item in value)


def derive_backup(source: dict, override: dict) -> dict:
    """Translate the root opt-in feature to the Swarm coordinator's mounted contract."""
    service = copy.deepcopy(source['services']['appflowy_backup'])
    if service.pop('profiles', None) != ['backup']:
        raise ValueError('Backup must remain opt-in in the root Compose source.')
    convert_environment('appflowy_backup', service)
    source_environment = environment_map(service.get('environment', {}))
    settings = copy.deepcopy(override['services']['appflowy_backup'])
    settings.pop('depends_on', None)
    settings.pop('volumes', None)
    settings_environment = environment_map(settings.pop('environment', {}))
    service.update(settings)
    service.pop('restart', None)
    service['environment'] = {
        **source_environment,
        **settings_environment,
        # Legacy stack interpolation does not support nested Compose fallback expressions.
        'APPFLOWY_BACKUP_BUCKET': '${APPFLOWY_BACKUP_BUCKET:?Set the private Backup artifact bucket}',
        'APPFLOWY_BACKUP_DEPLOYMENT': 'swarm',
        'APPFLOWY_BACKUP_SWARM_STACK': '${APPFLOWY_SWARM_STACK:-appflowy-swarm}',
        'APPFLOWY_BACKUP_WORK_DIR': '/var/lib/appflowy-backup/work',
        'APPFLOWY_BACKUP_RESTORE_DIRECTORY': '/var/lib/appflowy-backup/restore',
        'APPFLOWY_BACKUP_SWARM_RUNTIME_DIRECTORY': '/appflowy-deployment/backup-ops/swarm-runtime',
        'APPFLOWY_BACKUP_SEARCH_INDEX_DIR': '/var/lib/appflowy/keyword_index',
        'APPFLOWY_BACKUP_SERVICE_SOCKET': '/var/run/appflowy-backup/service.sock',
        'APPFLOWY_BACKUP_COORDINATOR_SOCKET': '/var/run/appflowy-backup/coordinator.sock',
    }
    service['volumes'] = [
        'backup_work:/var/lib/appflowy-backup',
        'backup_coordinator_socket:/var/run/appflowy-backup',
        'keyword_index_data:/var/lib/appflowy/keyword_index',
        '/var/run/docker.sock:/var/run/docker.sock',
        '${APPFLOWY_SWARM_BACKUP_RUNTIME_DIR:?Set the absolute Swarm backup runtime directory}:/appflowy-deployment/backup-ops/swarm-runtime',
    ]
    service['deploy'] = {
        # Start explicitly after GoTrue, Cloud migrations, Worker and Search are ready.
        'replicas': 0,
        'restart_policy': {'condition': 'any'},
        'update_config': {'parallelism': 1, 'order': 'stop-first'},
        'placement': {'constraints': [DATA_CONSTRAINT, 'node.role == manager']},
    }
    cloud = copy.deepcopy(override['services']['appflowy_cloud'])
    cloud['environment']['APPFLOWY_BACKUP_BUCKET'] = service['environment']['APPFLOWY_BACKUP_BUCKET']
    return {'version': '3.8', 'services': {'appflowy_cloud': cloud, 'appflowy_backup': service},
            'volumes': {'backup_work': None, 'backup_coordinator_socket': None}}


def check_parity(source: dict, stack: dict) -> None:
    """Compare every root field, allowing only the declared compatibility edits."""
    services = supported_services(source)
    if set(stack['services']) != set(services):
        raise ValueError('Service set differs from supported root Compose services.')
    for name, original in services.items():
        actual = copy.deepcopy(stack['services'][name])
        actual.pop('deploy')
        expected = copy.deepcopy(original)
        convert_environment(name, expected)
        expected.pop('restart', None)
        expected.pop('depends_on', None)
        if name == 'nginx':
            expected.pop('volumes')
            actual.pop('configs')
            actual.pop('secrets')
        if actual != expected:
            raise ValueError(f'Unexpected service configuration drift: {name}')
    for name, value in source.items():
        if name != 'services' and stack.get(name) != value:
            raise ValueError(f'Unexpected top-level configuration drift: {name}')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the committed counterpart differs from the source-derived output.')
    args = parser.parse_args()
    source = yaml.safe_load(SOURCE.read_text())
    generated = derive(source)
    check_parity(source, generated)
    backup = derive_backup(source, yaml.safe_load(BACKUP_SOURCE.read_text()))
    text = HEADER + yaml.safe_dump(generated, sort_keys=False, width=120)
    backup_text = (
        '# Generated by python3 docker-swarm/generate.py from root Compose Backup settings.\n'
        '# Opt-in single-manager Backup. Read README.md#backup-and-restore before enabling.\n'
        '# Start Backup after application readiness: docker service scale <stack>_appflowy_backup=1\n'
        + yaml.safe_dump(backup, sort_keys=False, width=120)
    )
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != text:
            print('FAIL: docker-swarm/docker-stack.yml is stale. Run: python3 docker-swarm/generate.py', file=sys.stderr)
            return 1
        if not BACKUP_TARGET.exists() or BACKUP_TARGET.read_text() != backup_text:
            print('FAIL: docker-swarm/docker-stack.backup.yml is stale. Run: python3 docker-swarm/generate.py', file=sys.stderr)
            return 1
        # Compare the actual parsed artifact as well as deterministic bytes.
        check_parity(source, yaml.safe_load(TARGET.read_text()))
    else:
        TARGET.write_text(text)
        BACKUP_TARGET.write_text(backup_text)
    count = len(generated['services'])
    dependencies = sum('depends_on' in service for service in source['services'].values())
    action = 'checked' if args.check else 'generated'
    print(f'PASS: {action} {TARGET.relative_to(ROOT)}; {count} application services retained (including AI); Backup retained in its opt-in Swarm overlay.')
    print('Parity: images, environment, commands, health checks, ports, and application volumes match root Compose.')
    print(f'Compatibility edits: v3.8/overlay, {dependencies} dependency blocks removed, restart/deploy policies, '
          '3 data-node constraints, Nginx configs/TLS secret, and opt-in Swarm Backup and Compose restore-state exclusions.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
