#!/usr/bin/env python3
"""Derive the Swarm counterpart from the root Compose source of truth.

Compatibility exceptions are intentionally narrow:
* Swarm uses legacy Compose v3.8 and an overlay network.
* Compose startup dependencies are removed; Swarm does not sequence readiness.
* restart becomes deploy.restart_policy, with one replica and stop-first updates.
* Local PostgreSQL, MinIO, and Search volumes require a labeled data node.
* Nginx's three repository file mounts become configs and a TLS key secret.

Images, environment, commands, health checks, ports, and application volumes
otherwise remain identical. Optional features, including AI, remain present.
Test-only settings belong in the local test overlay, never in this counterpart.
This file never reads .env or resolves environment variables.
"""
from __future__ import annotations

import argparse
import copy
from pathlib import Path
import sys

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'docker-compose.yml'
TARGET = Path(__file__).resolve().parent / 'docker-stack.yml'
DATA_SERVICES = {'postgres', 'minio', 'appflowy_search'}
DATA_CONSTRAINT = 'node.labels.appflowy.data == true'
HEADER = (
    '# Generated by python3 docker-swarm/generate.py from ../docker-compose.yml.\n'
    '# Do not edit this file; update the root Compose source and regenerate.\n'
    '# Swarm startup sequencing and data-node labeling are documented in README.md.\n'
)


def derive(source: dict) -> dict:
    stack = {'version': '3.8', **copy.deepcopy(source)}
    for name, service in stack['services'].items():
        service.pop('depends_on', None)
        restart = service.pop('restart', 'no')
        conditions = {'no': 'none', 'on-failure': 'on-failure', 'always': 'any', 'unless-stopped': 'any'}
        if restart not in conditions:
            raise ValueError(f'Unsupported restart policy for {name}: {restart}; update the compatibility conversion explicitly.')
        if 'deploy' in service:
            raise ValueError(f'{name} now defines deploy in the source; review how it merges with Swarm defaults.')
        service['deploy'] = {
            # Swarm defaults to one replica. Older Docker CLIs incorrectly merge
            # an explicit 1 with a bootstrap override of 0, retaining the 1.
            'restart_policy': {'condition': conditions[restart]},
            'update_config': {'parallelism': 1, 'order': 'stop-first'},
        }
        if name in DATA_SERVICES:
            service['deploy']['placement'] = {'constraints': [DATA_CONSTRAINT]}

    nginx = stack['services']['nginx']
    expected_mounts = [
        './docker/nginx/nginx.conf:/etc/nginx/nginx.conf',
        './docker/nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt',
        './docker/nginx/ssl/private_key.key:/etc/nginx/ssl/private_key.key',
    ]
    if nginx.get('volumes') != expected_mounts:
        raise ValueError('Root Nginx mounts changed; update the explicit configs/secrets conversion before regenerating.')
    if 'configs' in source or 'secrets' in source or 'networks' in source:
        raise ValueError('Root networks/configs/secrets changed; review their Swarm conversion explicitly.')
    nginx.pop('volumes')
    nginx['configs'] = [
        {'source': 'nginx_config', 'target': '/etc/nginx/nginx.conf'},
        {'source': 'tls_certificate', 'target': '/etc/nginx/ssl/certificate.crt'},
    ]
    nginx['secrets'] = [
        {'source': 'tls_private_key', 'target': '/etc/nginx/ssl/private_key.key', 'mode': 0o400},
    ]
    stack['networks'] = {'default': {'driver': 'overlay'}}
    stack['configs'] = {
        'nginx_config': {'file': '../docker/nginx/nginx.conf'},
        'tls_certificate': {'file': '../docker/nginx/ssl/certificate.crt'},
    }
    stack['secrets'] = {'tls_private_key': {'file': '../docker/nginx/ssl/private_key.key'}}
    return stack


def check_parity(source: dict, stack: dict) -> None:
    """Compare every root field, allowing only the declared compatibility edits."""
    if set(stack['services']) != set(source['services']):
        raise ValueError('Service set differs from root Compose.')
    for name, original in source['services'].items():
        actual = copy.deepcopy(stack['services'][name])
        actual.pop('deploy')
        expected = copy.deepcopy(original)
        expected.pop('restart', None)
        expected.pop('depends_on', None)
        if name == 'nginx':
            expected.pop('volumes')
            actual.pop('configs')
            actual.pop('secrets')
        if actual != expected:
            raise ValueError(f'Unexpected service configuration drift: {name}')
    for name, value in source.items():
        if name != 'services' and stack.get(name) != value:
            raise ValueError(f'Unexpected top-level configuration drift: {name}')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the committed counterpart differs from the source-derived output.')
    args = parser.parse_args()
    source = yaml.safe_load(SOURCE.read_text())
    generated = derive(source)
    check_parity(source, generated)
    text = HEADER + yaml.safe_dump(generated, sort_keys=False, width=120)
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != text:
            print('FAIL: docker-swarm/docker-stack.yml is stale. Run: python3 docker-swarm/generate.py', file=sys.stderr)
            return 1
        # Compare the actual parsed artifact as well as deterministic bytes.
        check_parity(source, yaml.safe_load(TARGET.read_text()))
    else:
        TARGET.write_text(text)
    count = len(source['services'])
    dependencies = sum('depends_on' in service for service in source['services'].values())
    action = 'checked' if args.check else 'generated'
    print(f'PASS: {action} {TARGET.relative_to(ROOT)}; all {count} root services retained (including AI).')
    print('Parity: images, environment, commands, health checks, ports, and application volumes match root Compose.')
    print(f'Compatibility edits: v3.8/overlay, {dependencies} dependency blocks removed, restart/deploy policies, '
          '3 data-node constraints, and Nginx configs/TLS secret.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
